accordion/urls.py
from django.urls import path
from . import views

appname = 'accordion'

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.story9, name='story9'),
    path('story10/', views.story10, name='story10')
]

story10/urls.py
from django.urls import path
from . import views

app_name = 'story10'

urlpatterns = [
    path('story10/', views.index, name='index'),
    path('signup/', views.signup,name='signup'),
    path('main/', views.main,name='main'),
    path('logout/',views.logout,name='logout')
]

story8/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accordion.urls')),
    path('books/', include('story9.urls')),
    path('story10/', include('story10.urls'))
]

story9/urls.py
from django.urls import path
from . import views
from .views import books, data

app_name = 'story9'

urlpatterns = [
    path('books/', views.books, name='books'),
    path('data/', data, name='books_data'),
    # dilanjutkan ...
]

accordion/models.py
from django.db import models

# Create your models here.

story10/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    id = models.CharField(max_length=130, primary_key=True)
    cover = models.CharField(max_length=400)
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200, blank=True)
    likes = models.IntegerField(default=0)

accordion/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

# Create your views here.
def index(request):
    return render(request, 'landing.html')

def story9(request):
    return render(request, 'books.html')

def story10(request):
    return redirect(reverse('story10:index'))

story10/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
import json
import requests
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth import logout as django_logout

# Create your views here.

def index(request):

	if(request.method=='GET'):

		return render(request, 'story10.html')
	else:
		username=request.POST.get("Username")
		password=request.POST.get("Password")

		user=authenticate(username=username,password=password)
		if(user is not None):
			login(request,user)
			return redirect('story10:main')
		messages.error(request,"Incorrect username/password")
		return render(request,'story10.html')

def signup(request):

	if(request.method == 'GET'):
			return render(request, 'Account.html')
		
	else:
		username= request.POST.get("Username")
		password=request.POST.get("Password")
		try:
			user = User.objects.get(username=username)
			messages.error(request,"Sorry username is already taken :(")
			return render(request,'Account.html')
		except:
			user=User.objects.create_user(username=username,password=password)
			messages.success(request,"You have succesfully created a new account")

			
			return redirect(reverse('story10:index'))

@login_required(login_url='story10:index')
def main(request):
	if(request.method=='GET'):
		return render(request,'Logout.html')

def logout(request):
	django_logout(request)
	return redirect('story10:index')

story9/views.py
from django.shortcuts import render
from django.http import JsonResponse
import json
import requests
from .models import Book
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def books(request):
    return render(request, 'books.html')

def data(request):
    try:
        q = request.GET['q']
    except:
        q = "quilting"
    
    json_read = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + q).json()

    return JsonResponse(json_read)

accordion/templates/landing.html
{% load static %}

<!DOCTYPE html>
<head>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">
    <title>Calmeryan's Profile</title>
</head>

<body>
    <div class="container">
        <div class="judul">
            Calmeryan's Profile
            <a href="{% url 'story9' %}"><button>story9</button></a>
            <a href="{% url 'story10' %}"><button name="btn-story10">story10</button></a>
        </div>
    
    <div class="accord">
    <ul>
        <li>
            <button onclick="up()" name="up1"><img class="atas"></button>
            <button onclick="down()" name="down1"><img class="bawah"></button>
            <button class="accordion judul-accord" name="aktivitas">Aktivitas</button>
            
            <div class="panel">
                <div class="isi-accord">
                    <p>Belajar</p>
                    <p>Bermain</p>
                    <p>Beristirahat</p>
                </div>
            </div>
        </li>
        
        <li>
            <button onclick="up()" name="up2"><img class="atas"></button>
            <button onclick="down()" name="down2"><img class="bawah"></button>
            <button class="accordion judul-accord" name="pengalaman">Pengalaman</button>
            
            <div class="panel isi-accord">
                <p>Sekolah BEM Fasilkom Depor</p>
                <p>Panitia PERAK Bis-Dev</p>
                <p>Panitia Compfest Sponsorship</p>
            </div>
        </li>

        <li>
            <button onclick="up()" name="up3"><img class="atas"></button>
            <button onclick="down()" name="down3"><img class="bawah"></button>
            <button class="accordion judul-accord" name="prestasi">Prestasi</button>
            
            <div class="panel isi-accord">
                <p>Peringkat 3 Nilai UN tertinggi di SD Tunas Karya 2 tahun 2013</p>
            </div>
        </li>

        <li>
            <button onclick="up()" name="up4"><img class="atas"></button>
            <button onclick="down()" name="down4"><img class="bawah"></button>
            <button class="accordion judul-accord" name="hobi">Hobi</button>
            
            <div class="panel isi-accord">
                <p>Makan</p>
                <p>Main games</p>
                <p>Streaming Youtube</p>
            </div>
        </li>
    </ul>
    </div>
    </div>


    <script>
        $('.button-up').click(function(){
            var thisAccordion = $(this).parent().parent().parent();
            thisAccordion.insertBefore(thisAccordion.prev());
        })

        $('.button-down').click(function(){
            var thisAccordion = $(this).parent().parent().parent();
            thisAccordion.insertAfter(thisAccordion.next());
        })
    </script>
    <script src="{% static 'jquery-3.5.0.min.js' %}"></script>
    <script src="{% static 'accord.js' %}"></script>
</body>

story10/templates/Account.html
{% load static %}

<!DOCTYPE html>
<head>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">
    <title>Sign Up</title>
</head>

<body>
    <div class="container">
        <div class="judul">
            Create Your Account
        </div>
        <br>

        <div class="isi">
            <form method="POST">
                <div class="form-group">
                   {% csrf_token %}
                   <label>Username:</label>
                   <input name="Username" id="Username" type="text" required>
                </div>
                <br>
                <div class="form-group">
                    <label>Password: </label>
                    <input name="Password" id="Password" type="password" required>
                </div>
                <br>
                <div class="form-group">
                  <input type="submit" value="Create Account" id="log-in" class="btn btn-warning" name="signup">
                    {% for i in messages %}
                    {{ i }}
                    {% endfor %}
                </div>
              </form>
        </div>
    </div>
    

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
</body>

story10/templates/Logout.html
{% load static %}

<!DOCTYPE html>
<head>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">
    <title>Hello {{ user.username }}! </title>
</head>

<body>
    <div class="judul">
        Hello {{ user.username }}!
    </div>

    <div class="isi">
        {% for i in messages %}
            {{ i }}
        {% endfor %}
            <br>
            <a href="{% url 'story10:logout' %}">
            <input type="submit" value="Log Out" class="btn btn-danger">
            </a>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
</body>

story10/templates/story10.html
{% load static %}

<!DOCTYPE html>
<head>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">
    <title>Story 10</title>
</head>

<body>
    <div class="container">
        <div class="judul">
            {% for i in messages %}
            {{ i }}
            {% endfor %}
            <br>
            Enter Your Account
        </div>
        <br>
        <div class="isi">
            <form method="POST">
                <div class="form-group">
                    {% csrf_token %}
                    <label>Username:</label>
                    <input name="Username" id="Username" type="text" required>
                </div>
                <br>
                <div class="form-group">
                    <label>Password: </label>
                    <input name="Password" id="Password" type="password" required>
                </div>
                <br>
                <div class="form-group">
                    <input type="submit" value="Log In" id="log-in" name="login" class="btn btn-warning">
                </div>
               
            </form>
        </div>

        <br>
        <div class="judul">
            Don't Have an Account?
        </div>

        <div class="isi">
            <br>
            <a href = "{% url 'story10:signup' %}">
                <input type="submit" value="Create Account" class="btn" name="signbut" style="background-color: rgb(137, 137, 145);">
            </a>
            
        </div>
        
    </div>


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
</body>

story9/templates/books.html
{% load static %}

<!DOCTYPE html>
<head>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">
    <title>Story 9</title>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script src="{% static 'story9.js' %}"></script>
</head>

<body>
    <div class="container">
        <div class="judul">
            Daftar Buku
        </div>
        <br>
        <div class="input">
            <input type="text" id="input" placeholder="Cari Buku.." title="Type in a name">
        </div>

        <div class="isi">
            <table id="demo" class="table table-borderless">
                <thead>
                    <tr>
                        <th scope="col" class="align-middle">No.</th>
                        <th scope="col" class="align-middle">Cover</th>
                        <th scope="col" class="align-middle">Title</th>
                        <th scope="col" class="align-middle">Authors</th>
                        <th scope="col" class="align-middle">Publisher</th>
                        <th scope="col" class="align-middle">Published Date</th>
                        <th scope="col" class="align-middle">Likes</th>
                    </tr>
                </thead>
                <tbody id="isi"></tbody>
            </table>
        </div>
    </div>

    
</body>